### PR TITLE
Add SBS in edit mode, add on/off toggling

### PR DESCRIPTION
**Pull request by szego**
Add the ability to edit existing questions/answers in side-by-side mode.

Also, add the ability to toggle side-by-side editing on an off for each
individual question/answer on the page.

### CODE REVIEW

**Comment by szego** [comment]
I've tested this on all the pages I could think of and it seems to be working well. I'm not that familiar with javascript/jQuery though and I would definitely appreciate another pair of eyes on it.

**Comment by shu8** [comment]
@szego firstly: thanks a lot! You must have spent some time doing that! :) 

Secondly: I will look at this over the weekend, looking at the code and result. It will probably work, but just to be safe! :)

Thanks again! :)

**Comment by szego** [comment]
@shu8 Just wanted to give you an update. I've refactored the code considerably to make it easier to edit and add to the CSS changes that happen when side-by-side editing is toggled on and off. A summary can be found here: szego/SE-Answers_scripts#1

Cheers

**Comment by shu8** [comment]
Thanks for that update @szego. I've merged it! :)

**Comment by shu8** [comment]
BTW I also use this feature in my https://github.com/shu8/SE_OptionalFeatures userscript. I'll update that with this version as well! :) I've done so on my local copy, but I'm ironing out a few other bugs I've got with that before I push it to the develop branch :)

**Comment by szego** [comment]
Great :). Would you mind if I add an answer to your post in StackApps to describe the new behavior?

**Comment by shu8** [comment]
Sure! It's your code ;) (Just mention that it starts in v1.7 please!)

**Comment by shu8** [comment]
Sorry -- I thought you were talking about the SE Optional Features one, but yeah -- you can post it on http://stackapps.com/questions/6461/side-by-side-editing, which I think you were actually talking about! 
(no need for that version thing!) :)

**Comment by shu8** [comment]
@szego I've updated my SE Additional Optional Features userscript! It's now in v1.7 (DEV) :) Thanks again!

**Pull request merged**
